services:
  - type: web
    name: whatsapp-song-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: GENIUS_ACCESS_TOKEN
        value: _P3ZN4p35QKNLFEIAGUuDF4OtqoE5CIvlV4xEvMCq8z6mkEtthujwCs_HuKdMU_J
        sync: true  # set manually via dashboard

